### ISSUE TITLE
Add option for brake times.

### ISSUE THREAD

**Issue by emskigdot** [dotcs/worklog#3]
If working hours < 6h, add 15 min brake
If working hours > 6h, add 45 min brake,

**Comment by dotcs** [comment]
Thanks for this PR. Since [version 0.0.23](https://github.com/dotcs/worklog/releases/tag/0.0.23) it's possible to define breaks that are automatically applied in the `status` and `report` commands.

See the additional configuration options which can be overwritten in your custom configuration:
https://github.com/dotcs/worklog/blob/45b1a02b312f7b8e5d3922c46f9bd8d3ec83b612/worklog/config.cfg#L16-L22
